### ISSUE TITLE
Will could provide an google cloud /baidu cloud download? 

### ISSUE THREAD

**Issue by Solacex** [xiaoaoran/SynLiDAR#1]
Hello,

Thanks for your awesome work. Will you consider releasing this dataset on google/Baidu cloud? We found it difficult to download such a large dataset from the current server. 

Thanks.

**Comment by xiaoaoran** [comment]
We will upload to baiduyun for users in mainland China. Thank you for the notice.

**Comment by Solacex** [comment]
Thank you ~
