### ISSUE TITLE
About the dataset used in paper

### ISSUE THREAD

**Issue by dream-toy** [xiaoaoran/SynLiDAR#10]
Hi, Aoran Xiao.
Thank you for your brilliant work.

I see that "-- SubDataset: uniformlly downsampled dataset (about 24GB), this is the dataset that we used in [Paper](https://arxiv.org/abs/2107.05399). You are recommend to use this smaller dataset for faster experiments." in readme file.

To fairly compare with your method, I would like to confirm that all the experimental results in your paper "Transfer Learning from Synthetic to Real LiDAR Point Cloud for Semantic Segmentation" use SubDataset?

**Comment by xiaoaoran** [comment]
Yes, we used the SubDataset in the paper.
