### ISSUE TITLE
Could you provide more information about intensity rendering model?

### ISSUE THREAD

**Issue by Beastmaster** [xiaoaoran/SynLiDAR#13]
I noticed on you paper that "Detailed descriptions about the rendering model and experiments are presented in Appendix" but I can't find the appendix nowhere. Could you kindly provide some more information about that?
Thanks!

**Comment by xiaoaoran** [comment]
Hi！ Thanks for your interest in our work!

Please find details of intensity rendering in this [file](https://drive.google.com/file/d/1QVV4rTsXLV82Nwj4jgrEDgeVOW8jiSoB/view?usp=sharing).
