### ISSUE TITLE
LiDAR sensor specification

### ISSUE THREAD

**Issue by BjoernMichele** [xiaoaoran/SynLiDAR#14]
Thank you very much for the interesting work and providing the dataset. 

I was wondering, which LiDAR sensor you simulated  (if you had a specific selected) when generating the dataset or if you have the specifications (like angles, number of beams , number of points per beam) of the sensor that you simulate. 

Thank you very much again. 
Best,

**Comment by xiaoaoran** [comment]
Hi @BjoernMichele 

Thanks for your interest in our work!

We used AirSim for LiDAR simulation and you may find details in this [file](https://drive.google.com/file/d/1QVV4rTsXLV82Nwj4jgrEDgeVOW8jiSoB/view?usp=sharing).

**Comment by BjoernMichele** [comment]
Thank you very much for your answer.
