### ISSUE TITLE
Download issue 

### ISSUE THREAD

**Issue by Solacex** [xiaoaoran/SynLiDAR#2]
![image](https://user-images.githubusercontent.com/12868455/127856680-f55436dd-1f15-45c3-a48d-c7c44968ad6a.png)
Hello, 

Thanks for your awesome work. Now I am trying to download the dataset using the provided download.py. 
However, as shown in the above figure, the size of all downloaded subsets could not exceed 5.9 GB, so I want to if there is any constraint on the server or any other things I should check. 

Thanks

**Comment by xiaoaoran** [comment]
Hi.

This is strange, I tried again and it's okay to download full-sized data. Did your server have any restrictions for downloading big-sized files?

By the way, we have shared baiduyun link and you can also download from this way.

**Comment by Solacex** [comment]
It seems that there may be some constraint on the server. I have downloaded other larger files, but I haven't met such problem.  
It also stops at the some place. 
![image](https://user-images.githubusercontent.com/12868455/128282545-f9275b82-1fdb-421e-83d2-dafd52b50268.png)

**Comment by Solacex** [comment]
Is there any constraint on the connection of your server? it seems always stop after downloading for around 1 hour

**Comment by xiaoaoran** [comment]
Thank you for the notice. We are contacting the admin for this problem. You can download it from Baiduyun during this time period.

**Comment by Solacex** [comment]
It seems that there is indeed a time-out constraint on the NTU server, thanks for offering the Baiduyun version. But I want to know if there will be a google drive version? 

It's okay if you don't plan to upload it to google drive, I am asking this just because google drive is more convenient for me.

**Comment by Solacex** [comment]
By the way, it would also be great if you could split the dataset into more small splits on your server. Just a suggestion.

**Comment by xiaoaoran** [comment]
Thank you for the suggestions. 

We will consider uploading it to google drive in the near future.

Yes, the NTU server does have restrictions for downloading time, we will split it into much smaller files.

Thanks again.
