### ISSUE TITLE
Question about the class mapping

### ISSUE THREAD

**Issue by kongxin123456** [xiaoaoran/SynLiDAR#8]
Hi, Aoran Xiao. 
Firstly, thank you for your brilliant work! I see that you have given an example of class mapping from synlidar to semantickitti. And could you share the YAML file of semanticPOSS with me too? Please help.

**Comment by xiaoaoran** [comment]
Hi Kongxin, I have updated the 'annotations.yaml' file, you can find the mapping from synlidar to semanticposs now.
